/* This file has been automatically generated by RPC-Generator
   https://github.com/Crystal-Photonics/RPC-Generator
   You should not modify this file manually. */


#include <stdint.h>
#include "RPC_client.h"

RPC_RESULT square(int32_t return_value_out[1], int32_t i){
	/***Serializing***/
		RPC_push_byte(2); /* save ID */

		/* writing integral type int32_t i of size 4 */
		RPC_push_byte(i);
		RPC_push_byte(i >> 8);
		RPC_push_byte(i >> 16);
		RPC_push_byte(i >> 24);


	/***Communication***/
		RPC_commit();
		if (!(RPC_SLEEP()))
			return RPC_FAILURE;

	/***Deserializing***/
				
		/* reading integral type int32_t *return_value_out of size 4 */
		*return_value_out = current++;
		*return_value_out |= (*current++) << 8;
		*return_value_out |= (*current++) << 16L;
		*return_value_out |= (*current++) << 24L;

		return RPC_SUCCESS;
}

RPC_RESULT test(int32_t return_value_out[1], uint16_t data_inout[42]){
	/***Serializing***/
		RPC_push_byte(4); /* save ID */

		/* writing array data_inout with 42 elements */
		{
			int RPC_COUNTER_VAR2;
			for (RPC_COUNTER_VAR2 = 0; RPC_COUNTER_VAR2 < 42; RPC_COUNTER_VAR2++){

				/* writing integral type uint16_t data_inout[RPC_COUNTER_VAR2] of size 2 */
				RPC_push_byte(data_inout[RPC_COUNTER_VAR2]);
				RPC_push_byte(data_inout[RPC_COUNTER_VAR2] >> 8);

			}
		}

	/***Communication***/
		RPC_commit();
		if (!(RPC_SLEEP()))
			return RPC_FAILURE;

	/***Deserializing***/
				
		/* reading integral type int32_t *return_value_out of size 4 */
		*return_value_out = current++;
		*return_value_out |= (*current++) << 8;
		*return_value_out |= (*current++) << 16L;
		*return_value_out |= (*current++) << 24L;

		/* reading array data_inout with 42 elements */
		{
			int RPC_COUNTER_VAR2;
			for (RPC_COUNTER_VAR2 = 0; RPC_COUNTER_VAR2 < 42; RPC_COUNTER_VAR2++){

				/* reading integral type uint16_t data_inout[RPC_COUNTER_VAR2] of size 2 */
				data_inout[RPC_COUNTER_VAR2] = current++;
				data_inout[RPC_COUNTER_VAR2] |= (*current++) << 8;

			}
		}
		return RPC_SUCCESS;
}

